{{- if not (include "newrelic.licenseCustomSecretName" .) | and (include "newrelic.licenseKey" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otel-k8s-prometheus.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-k8s-prometheus.labels" . | nindent 4 }}
data:
  licenseKey: {{ include "newrelic.licenseKey" . | b64enc }}
{{- end }}
